version: "3.8"

services:
  redis:
    image: redis/redis-stack
    container_name: redis
    restart: always
    command: redis-server --loglevel warning --protected-mode no --loadmodule /opt/redis-stack/lib/rejson.so --loadmodule /opt/redis-stack/lib/redisearch.so
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  redis_data: {}
